name: release
run-name: Release run ${{ github.run_number }}
# thanks to Jan Mosig, see https://blogs.itemis.com/en/github-actions-releasing-artifacts-into-maven-central
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        type: choice
        required: true
        default: 'minor'
        options: ['minor', 'hotfix']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      checks: write
      packages: write

    env:
      RELEASE_TYPE: ${{ inputs.release-type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: unnecessary # we are only connecting to github, which is already in known_hosts
      - name: Setup the git user
        run: |
          git config --global user.name "${{ vars.RELEASE_BOT_NAME }}"
          git config --global user.email "${{ vars.RELEASE_BOT_EMAIL }}"
          git config --global gpg.format ssh
          git config --global user.signingkey "${{ vars.SSH_PUBLIC_KEY }}"
          git config --global commit.gpgsign true
          git config --global tag.gpgsign true
          ssh-add -L
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: true
      - name: Setup Java
        uses: actions/setup-java@v3 # Does also set up Maven and GPG
        with:
          java-package: 'jdk'
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          check-latest: true
          server-id: 'ossrh' # must match the serverId configured for the nexus-staging-maven-plugin
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: SIGN_KEY_PASS
      - name: Prepare and tag
        run: |
          mvn -U -B clean release:prepare -P sxda-release
        env:
          SIGN_KEY_PASS: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      - name: Publish
        run: |
          mvn -U -B release:perform -P sxda-release
        env:
          SIGN_KEY_PASS: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
